version: '{build}'

image: Visual Studio 2015

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 14 2015"
    QT5: C:\Qt\5.8\msvc2015
  - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
    QT5: C:\Qt\5.8\msvc2015_64

matrix:
  fast_finish: true

before_build:
  - set Path=%QT5%\bin;%Path%
  - cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" -DCMAKE_SYSTEM_VERSION=10.0 "-DCMAKE_PREFIX_PATH=%QT5%"

build_script:
  - if "%APPVEYOR_REPO_TAG%"=="true" (set CONFIGURATION=RelWithDebInfo) else (set CONFIGURATION=Debug)
  - cmake --build build --config "%CONFIGURATION%" -- %MSBUILD_FLAGS%

after_build:
  - build\bin\%CONFIGURATION%\tests.exe

artifacts:
  - path: build/bin/
